### PR TITLE
add auto-tiling and fix weighting after merging

### PR DESCRIPTION
**Pull request by renerichter**
I just briefly checked into the mechanism of the toolbox and added some-functions which might do the intended trick for: 

- automatic calculation of necessary padding (and shape)
- re-weighting after merging

. The code is implemented for 3D-images (hence for a 2D-image eg [1,y,x] could be provided) and needs to be slightly adjusted to work for 2D or ND. 
Things to be done: 

- proper docstrings
- catching user-input-errors
- deleting unnecessary functions and clean-up

Further points are mentioned in the opened issue. :)

### CODE REVIEW

**Comment by the-lay** [comment]
Great job! I very sorry I am slow to respond, but I promise to thoroughly go through all your changes this week.

Thank you for your work!

**Comment by renerichter** [comment]
Thank you very much and take your time. I think there are still several errors in there as well as points to be discussed. I [just added a function for automatic calculation](https://github.com/the-lay/tiler/pull/7/commits/fdc38c8de89c1e6802d7011350bea6f0ae9f6273) of a minimal overlap (if no overlap is given), but it is not yet implemented in the _init_ of Tiler class. Further, I fixed some small errors in the merger function.

**Comment by the-lay** [comment]
Hey, I've finally got around to work on tiler. Sorry it takes me so long :(

There were a lot of changes in master branch, so I merged it here and also did some new general changes (latter by mistake, but that's fine since I still want to merge this back to master eventually). I am now looking over your code/PR more thoroughly and want to finish this weekend.


> Hence: division by the weight map should be the right solution. what do you think?

I agree! But that shouldn't be default, rather a flag parameter in `Merger.merge` IMO.

> Would you mind to fix docstrings, check for ndimensionality of the code I suggested and add your suggested changes for passed elements and privacy of the functions? 

Sure, will focus on that now.

A question from me:
What do you mean by minimal overlap, could you explain `Tiler.calculate_minimal_overlap` method? After all, even overlap of 0 is fine, depends on the use cases.

**Comment by renerichter** [comment]
Hiho, no worries. I wanted to answer already two weeks ago but somehow didn't manage. Thank you for the merge and comments. 

> I agree! But that shouldn't be default, rather a flag parameter in Merger.merge IMO.
Why would this be better. I believe that people just want to tile an object, calculate whatever on each tile and then merge it back together with a neat overleap. Hence: a flag parameter that is set to active on default should be the way to go, or?

> What do you mean by minimal overlap, could you explain Tiler.calculate_minimal_overlap method? After all, even overlap of 0 is fine, depends on the use cases.
Actually, the function Tiler.`calculate_minimal_overlap` is a remnant of my approach towards the automated tiling calculation and I thought that having such a method for a given "total image size" + " amount of tiles to be split into" would be helpful. Then I decided (like was basically in the toolbox already) that rather having the user decide how big a tile (and the overlap) should be and from there on calculating amount and positions of tiles is more useful and straight forward. Hence: We can delete it.

On another note:
CI are active for this repo. Did you test and integrate them properly? Shall we have a further look and or test?

**Comment by the-lay** [comment]
I have pushed a big pack of commits. I have refactored your code to be a bit more end user friendly and consistent, hope you don't mind. I've added/modified tests, documentation, fixed CI on pull requests, and generally added few new features (sorry for doing that in your fork!). The last thing to do is to update examples (as overlap-tile can now be done slightly easier than before) :)

Now padding is applied through `Tiler.apple_padding` which replaces `calculate_padding()`, `pad_outer()` and `fix_data_shape()`. The applied padding is stored in `Tiler._padding` which gets read in `Merger.merge()`. I have also worked on normalization by weight. I think now it's a bit less complex, just a matter of setting flag `normalize_by_weights=True` in `Merger.merge()`.

Here's the adjusted code to [your code examples and figures](https://github.com/the-lay/tiler/issues/6#issuecomment-927658486) with the new changes:
<details>
  <summary>Under spoiler</summary>
  
  ```python
  import numpy as np
  from tiler import Tiler, Merger
  import matplotlib.pyplot as plt
  
  # %% Test example for online
  
  # parameter
  data_shape = [1, 256, 256]
  tile_shape = np.array([1, 64, 64])
  overlap = np.array([0, 7, 20])
  tiler_mode = 'wrap'
  windows_supported = ['boxcar', 'triang', 'blackman', 'hamming', 'hann', 'bartlett', 'parzen', 'bohman',
                       'blackmanharris', 'nuttall', 'barthann', 'overlap-tile']
  
  # image
  xy = np.ogrid[0:data_shape[-2], 0:data_shape[-1]]
  xy = np.sqrt(xy[0] * np.transpose(xy[0]) + xy[1] * np.transpose(xy[1]))
  im = np.cos(4 * xy * np.pi / np.max(xy))[np.newaxis]
  merged_images = [im, ]
  
  # tile me
  tiler = Tiler(data_shape=data_shape, tile_shape=tile_shape, overlap=tuple(overlap))
  im_padded = tiler.apply_padding(im)
  weights_sums = [np.ones(im_padded.shape), ]
  
  for mwin in windows_supported:
      merger = Merger(tiler, window=mwin)
      # Merger.SUPPORTED_WINDOWS == ['boxcar', 'triang', 'blackman', 'hamming', 'hann', 'bartlett', 'flattop', 'parzen', 'bohman', 'blackmanharris', 'nuttall', 'barthann', 'overlap-tile']
  
      for tile_id, tile in tiler(im_padded):
          processed_tile = tile  # lambda x: x
          merger.add(tile_id, processed_tile)
  
      imf = merger.merge()
      merged_images.append(imf)
      weights_sums.append(merger.weights_sum)
  
  # plot images
  merged_images = np.array(merged_images)[:, 0]
  fig, ax = plt.subplots(nrows=4, ncols=4, figsize=[14, 14])
  plt_titles = ['reference', ] + windows_supported
  axm = ax.flatten()
  for m, mim in enumerate(merged_images):
      ima = axm[m].imshow(mim, interpolation='None')
      axm[m].set_title(plt_titles[m])
  plt.suptitle('Resulting Images')
  plt.tight_layout()
  plt.show()
  
  # plot images
  weights_sums = np.array(weights_sums)
  fig2, ax2 = plt.subplots(nrows=4, ncols=4, figsize=[14, 14])
  plt_titles = ['reference', ] + windows_supported
  axm = ax2.flatten()
  with np.errstate(divide='ignore', invalid='ignore'):
      inv_weights = np.nan_to_num(weights_sums[0] / weights_sums)
  inv_weights /= np.max(inv_weights, axis=(-2, -1), keepdims=True)
  sl = [slice(pad_from, shape - pad_to) for shape, (pad_from, pad_to) in zip(tiler.data_shape, tiler._padding)]
  for m, invm in enumerate(inv_weights):
      ima = axm[m].imshow(invm[tuple(sl)][0] ** 0.002, interpolation='None')
      axm[m].set_title(plt_titles[m])
  plt.suptitle('Inverse Weights-maps **0.002 (for display)')
  plt.tight_layout()
  plt.show()
  
  # differences
  for m, mim in enumerate(merged_images):
      print(f"All close for window_func={plt_titles[m]}?\t {np.allclose(mim, im[0])}")
  ```
  
</details>

===

> Why would this be better. I believe that people just want to tile an object, calculate whatever on each tile and then merge it back together with a neat overleap. Hence: a flag parameter that is set to active on default should be the way to go, or?

After thinking about it some more, I believe you are right, thank you for defending the on point! On the first thought I thought it would not work when window is not specified, but it all works out nicely even then.

> `Tiler.calculate_minimal_overlap` is a remnant of my approach towards the automated tiling calculation and  I thought that having such a method for a given "total image size" + " amount of tiles to be split into" would be helpful. 

I actually like the idea! I was thinking about creating few Tiler class methods for auto overlap calculation and for auto tile shape calculation.

**Comment by the-lay** [comment]
I have pushed a big pack of commits. I have refactored your code to be a bit more end user friendly and consistent, hope you don't mind. I've added/modified tests, documentation, fixed CI on pull requests, and generally added few new features (sorry for doing that in your fork, but hopefully I can merge it back very soon!).

Now padding is applied through `Tiler.calculate_padding()`, see [the example here](https://github.com/the-lay/tiler/blob/c230be4bb205ba22041a498143d803d75033a6ac/tiler/tiler.py#L510). I have also worked on normalization by weight. I think now it's a bit less complex, just a matter of setting flag `normalize_by_weights=True` in `Merger.merge()`.

Here's the adjusted code to [your code examples and figures](https://github.com/the-lay/tiler/issues/6#issuecomment-927658486) with the new changes:
<details>
  <summary>Under spoiler</summary>
  
  ```python
import numpy as np
from tiler import Tiler, Merger
import matplotlib.pyplot as plt

# %% Test example for online

# parameter
data_shape = [1, 256, 256]
tile_shape = np.array([1, 64, 64])
overlap = np.array([0, 7, 20])
tiler_mode = 'wrap'
windows_supported = ['boxcar', 'triang', 'blackman', 'hamming', 'hann', 'bartlett', 'parzen', 'bohman',
                     'blackmanharris', 'nuttall', 'barthann', 'overlap-tile']


# image
xy = np.ogrid[0:data_shape[-2], 0:data_shape[-1]]
xy = np.sqrt(xy[0] * np.transpose(xy[0]) + xy[1] * np.transpose(xy[1]))
im = np.cos(4 * xy * np.pi / np.max(xy))[np.newaxis]
merged_images = [im, ]

# tile me
tiler = Tiler(data_shape=data_shape, tile_shape=tile_shape, overlap=overlap, channel_dimension=0)
new_shape, padding = tiler.calculate_padding()
tiler.recalculate(data_shape=new_shape)
im_padded = np.pad(im, padding, mode="reflect")
weights_sums = [np.ones(im.shape), ]

for mwin in windows_supported:
    merger = Merger(tiler, window=mwin)

    for tile_id, tile in tiler(im_padded):
        processed_tile = tile  # lambda x: x
        merger.add(tile_id, processed_tile)

    imf = merger.merge(extra_padding=padding)
    merged_images.append(imf)
    weights_sums.append(merger._unpad(merger.weights_sum, padding))

# plot images
merged_images = np.array(merged_images)[:, 0]
fig, ax = plt.subplots(nrows=4, ncols=4, figsize=[14, 14])
plt_titles = ['reference', ] + windows_supported
axm = ax.flatten()
for m, mim in enumerate(merged_images):
    ima = axm[m].imshow(mim, interpolation='None')
    axm[m].set_title(plt_titles[m])
plt.suptitle('Resulting Images')
plt.tight_layout()
plt.show()

# plot images
weights_sums = np.array(weights_sums)
fig2, ax2 = plt.subplots(nrows=4, ncols=4, figsize=[14, 14])
plt_titles = ['reference', ] + windows_supported
axm = ax2.flatten()
with np.errstate(divide='ignore', invalid='ignore'):
    inv_weights = np.nan_to_num(weights_sums[0] / weights_sums)
inv_weights /= np.max(inv_weights, axis=(-2, -1), keepdims=True)
for m, invm in enumerate(inv_weights):
    ima = axm[m].imshow(invm[0] ** 0.002, interpolation='None')
    axm[m].set_title(plt_titles[m])
plt.suptitle('Inverse Weights-maps **0.002 (for display)')
plt.tight_layout()
plt.show()

# differences
for m, mim in enumerate(merged_images):
    print(f"All close for window_func={plt_titles[m]}?\t {np.allclose(mim, im[0])}")

  ```
  
a
b
  
</details>

===

> Why would this be better. I believe that people just want to tile an object, calculate whatever on each tile and then merge it back together with a neat overleap. Hence: a flag parameter that is set to active on default should be the way to go, or?

After thinking about it some more, I believe you are right, thank you for defending the on point! On the first thought I thought it would not work when window is not specified, but it all works out nicely even then.

> `Tiler.calculate_minimal_overlap` is a remnant of my approach towards the automated tiling calculation and  I thought that having such a method for a given "total image size" + " amount of tiles to be split into" would be helpful. 

I actually like the idea! I was thinking about creating few Tiler class methods for auto overlap calculation and for auto tile shape calculation.

**Comment by renerichter** [comment]
Hey, thank you for all your efforts. Now the code looks way nicer. :)
Working on my fork is totally fine and thank you for already including the changes in the main-toolbox. 
Even though it was more or less only a wrapper I liked (for closeness of usage of the class) that applying the padding via ` im_padded = tiler.pad_outer(im, tiler.pads)` was possible in my code suggestion. Now the padding is again applied via `im_padded = np.pad(im, padding, mode="reflect")`, which is fine as well, but I liked the class-inherent usage a bit more as then the call could be standardized to `tiler.pad_outer()` which then internally applies `tiler.pads` to `im` and stores it (maybe) in another object called `tiler._im_padded`. Hence the user needs less and less to think about what is happening behind the scenes. What do you think?
Again: Thank you for all your refactoring work. :)

**Comment by the-lay** [comment]
I see how wrapping `np.pad` or storing padded image in object can be easier for users, but I think it might be restricting users too much.

For example, in segmentation tasks you can have many "layers" of the same data, e.g. RGB image and class mask. I'd create one tiling object, apply calculated padding to all images and then use the same Tiler object to tile multiple images. This wouldn't work with wrapped `np.pad` or hidden stored `im_padded`.

So I'd prefer to just explicitly return padding in the form that is easy to plug into `np.pad` and let user control storage too, since for some applications with very large arrays it might be critical.

I will merge this all into main branch later today and make a new version soon! Thank you very much for your help and discussions!

**Pull request merged**
